### ISSUE TITLE
routeData.As<Guid>("id") thrown Invalid cast exception

### ISSUE THREAD

**Issue by sonerturkkan** [CarterCommunity/Carter#106]
```
this.Get("/stock/{id:guid}", async (req, res, routeData) =>
{
     var myid = routeData.As<Guid>("id");  //thrown Invalid cast exception
     await res.Negotiate(myid);
});

```

> There has been an error
> System.InvalidCastException: Invalid cast from 'System.String' to 'System.Guid'.
>    at System.Convert.DefaultToType(IConvertible value, Type targetType, IFormatProvider provider)
>    at coster.api.ExRouteDataExtensions.AsGuid(RouteData routeData, String key) in 
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Carter.CarterExtensions.<>c__DisplayClass1_0.<<CreateRouteHandler>b__0>d.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>d__6.MoveNext()

**Comment by JoeStead** [comment]
Under the hood, it uses `Convert.ChangeType`, which apparently doesn't support guids. Would be keen to avoid adding in special clauses into the conversion logic, I wonder if something like: https://stackoverflow.com/a/393787/1324810 would work

**Comment by jchannon** [comment]
Could do. Would have to be careful with datetime by the looks of it

**Comment by jchannon** [comment]
Here's Nancy's approach https://github.com/NancyFx/Nancy/blob/c2aef9cd644e1850623b8ebf41706a5787568008/src/Nancy/DynamicDictionaryValue.cs#L95
